#!/bin/bash
# ==============================================================================
# setup-snapclient.sh
# Configura Snapclient en Proxmox/LXC/Debian con ALSA fijo, passthrough,
# asound.conf, control de volumen configurable y verificación automática.
# Autor: Josue / GPT-5 — v0.0.1
# ==============================================================================

set -e

# === FUNCIONES AUXILIARES ====================================================

detect_environment() {
  if command -v pct >/dev/null 2>&1; then
    echo "proxmox"
  elif grep -qa container=lxc /proc/1/environ 2>/dev/null; then
    echo "lxc"
  elif [[ -f /etc/debian_version ]]; then
    echo "debian"
  else
    echo "unknown"
  fi
}

detect_debian_codename() {
  grep VERSION_CODENAME= /etc/os-release | cut -d= -f2 2>/dev/null || echo "unknown"
}

detect_snap_version() {
  snapclient --version 2>/dev/null | head -n1 | awk '{print $3}' || echo "none"
}

get_suggested_snap_ver() {
  local codename="$1"
  case "$codename" in
    bullseye) echo "v0.29.0" ;;
    bookworm) echo "v0.33.0" ;;
    trixie) echo "v0.34.0" ;;
    *) echo "v0.33.0" ;;
  esac
}

pause() { read -rp "Presiona Enter para continuar..."; }

# === FIJAR ORDEN DE TARJETAS ALSA ============================================

fix_alsa_order() {
  echo "🔍 Detectando tarjetas ALSA en el host..."
  echo

  CARDS=()
  IDS=()

  for card in /proc/asound/card*/id; do
    cid=$(basename "$(dirname "$card")")
    name=$(cat "$card")
    CARDS+=("$cid")
    IDS+=("$name")
  done

  if [ ${#CARDS[@]} -eq 0 ]; then
    echo "❌ No se detectaron tarjetas ALSA. Abortando."
    return
  fi

  echo "🎧 Tarjetas detectadas:"
  for i in "${!CARDS[@]}"; do
    echo "  [${CARDS[$i]}] -> ${IDS[$i]}"
  done
  echo

  read -rp "👉 ¿Cuál tarjeta querés que sea la PRINCIPAL (card0)? (ej: Device o PCH): " MAIN
  read -rp "👉 ¿Y cuál será la SECUNDARIA (card1)? (dejá en blanco si solo hay una): " SECONDARY

  if ! grep -q "$MAIN" /proc/asound/card*/id; then
    echo "❌ No se encontró ninguna tarjeta con nombre '$MAIN'. Abortando."
    return
  fi

  CONF_FILE="/etc/modprobe.d/alsa-base.conf"
  BACKUP_FILE="/etc/modprobe.d/alsa-base.conf.bak_$(date +%Y%m%d%H%M%S)"
  [ -f "$CONF_FILE" ] && cp "$CONF_FILE" "$BACKUP_FILE" && echo "📦 Backup creado: $BACKUP_FILE"

  echo "🧩 Actualizando $CONF_FILE ..."
  echo "# Generated by setup-snapclient.sh on $(date)" > "$CONF_FILE"

  if lsmod | grep -q snd_usb_audio; then
    MOD_USB="snd_usb_audio"
  else
    MOD_USB="snd-usb-audio"
  fi
  if lsmod | grep -q snd_hda_intel; then
    MOD_HDA="snd_hda_intel"
  else
    MOD_HDA="snd-hda-intel"
  fi

  if [[ "$MAIN" =~ [Uu][Ss][Bb] || "$MAIN" =~ [Dd]evice ]]; then
    echo "options $MOD_USB index=0" >> "$CONF_FILE"
    echo "options $MOD_HDA index=1" >> "$CONF_FILE"
  else
    echo "options $MOD_HDA index=0" >> "$CONF_FILE"
    echo "options $MOD_USB index=1" >> "$CONF_FILE"
  fi

  echo
  echo "✅ Orden ALSA fijado correctamente."
  echo "🎯 card0 → $MAIN"
  [[ -n "$SECONDARY" ]] && echo "🎯 card1 → $SECONDARY"
  echo
  echo "⚙️  Reinicia el host para aplicar cambios."
  echo
}

# === CONFIGURAR SNAPCLIENT ===================================================

setup_snapclient() {
  ENVIRONMENT=$(detect_environment)

  if [ "$ENVIRONMENT" = "proxmox" ]; then
    echo ""
    echo "📦 Contenedores disponibles:"
    pct list | awk 'NR>1 {printf " - %s (%s)\n", $1, $2}'
    echo ""
    read -rp "Ingrese el ID del contenedor LXC destino: " CTID
    if ! pct status "$CTID" >/dev/null 2>&1; then
      echo "❌ El contenedor $CTID no existe."
      exit 1
    fi
    DEBIAN_VERSION=$(pct exec "$CTID" -- bash -c 'grep VERSION_CODENAME= /etc/os-release | cut -d= -f2' 2>/dev/null || echo "bookworm")
    INSTALLED_VER=$(pct exec "$CTID" -- bash -c 'snapclient --version 2>/dev/null | head -n1 | awk "{print \$3}"' || echo "none")
  else
    DEBIAN_VERSION=$(detect_debian_codename)
    INSTALLED_VER=$(detect_snap_version)
  fi

  SUGGESTED_VER=$(get_suggested_snap_ver "$DEBIAN_VERSION")

  echo ""
  echo "📦 Sistema Debian detectado: $DEBIAN_VERSION"
  echo "💡 Versión recomendada de Snapclient: $SUGGESTED_VER"
  echo "🔍 Versión instalada actual: $INSTALLED_VER"
  echo ""

  if [ "$ENVIRONMENT" = "proxmox" ]; then
    echo "🔍 Tarjetas de audio del host:"
    aplay -l | grep '^card' || echo "⚠️ No se detectaron tarjetas ALSA."
  else
    echo "🔍 Tarjetas locales:"
    aplay -l | grep '^card' || echo "⚠️ No se detectaron tarjetas ALSA."
  fi

  echo ""
  read -rp "Ingrese el número de tarjeta a usar (ej. 0=Interna, 1=DAC): " CARD_ID

  # === Nueva lógica automática para obtener dispositivo ALSA ===
  echo ""
  echo "🎧 Dispositivos disponibles en card $CARD_ID:"
  aplay -l | awk -v id=$CARD_ID '/^card/ && $2==id":" {print " - device " $6 ": " substr($0, index($0,$8))}' | sed 's/,//g'
  DEVICE_NUMS=($(aplay -l | awk -v id=$CARD_ID '/^card/ && $2==id":" {print $6}' | sed 's/,//'))
  if [ ${#DEVICE_NUMS[@]} -eq 0 ]; then
    echo "❌ No se detectaron dispositivos ALSA para card $CARD_ID."
    exit 1
  fi

  read -rp "Selecciona el número de dispositivo (ej. ${DEVICE_NUMS[0]}): " DEV_ID
  [[ -z "$DEV_ID" ]] && DEV_ID="${DEVICE_NUMS[0]}"

  CARD_NAME=$(aplay -l | awk -v id=$CARD_ID -F'[][]' '/card/{if ($2==id) print $4}')
  SAFE_CARD_NAME=$(echo "$CARD_NAME" | tr -d ' ')
  ALSA_DEVICE="plughw:CARD=$SAFE_CARD_NAME,DEV=$DEV_ID"

  echo "✅ Usando ALSA: $ALSA_DEVICE"
  echo ""

  read -rp "Ingrese la IP del Snapserver: " SNAPSERVER_IP
  read -rp "Ingrese el nombre del cliente Snapcast: " CLIENT_NAME
  read -rp "🎚️ Ingrese el volumen inicial (0–100)%: " VOLUME

  CARD_DESC=$(aplay -l | awk -v id=$CARD_ID -F'[][]' '/card/{if ($2==id) print $4}')

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "🧾 REVISIÓN FINAL DE CONFIGURACIÓN:"
  [[ "$ENVIRONMENT" == "proxmox" ]] && echo " Contenedor LXC:     $CTID"
  echo " Debian:            $DEBIAN_VERSION"
  echo " Snapclient actual: $INSTALLED_VER"
  echo " Snapclient nuevo:  $SUGGESTED_VER"
  echo " Tarjeta:           card $CARD_ID ($CARD_DESC)"
  echo " Dispositivo ALSA:  $ALSA_DEVICE"
  echo " Snapserver IP:     $SNAPSERVER_IP"
  echo " Nombre cliente:    $CLIENT_NAME"
  echo " Volumen inicial:   ${VOLUME}%"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  read -rp "¿Deseas aplicar esta configuración? (Y/n): " CONFIRM
  [[ "$CONFIRM" =~ ^[Nn]$ ]] && { echo "❌ Cancelado."; return; }

  if [ "$ENVIRONMENT" = "proxmox" ]; then
    CONF_FILE="/etc/pve/lxc/${CTID}.conf"
    if ! grep -q "/dev/snd" "$CONF_FILE"; then
      echo "⚙️ Agregando passthrough de /dev/snd..."
      cat <<EOF >> "$CONF_FILE"

# === Passthrough ALSA ===
lxc.cgroup2.devices.allow: c 116:* rwm
lxc.mount.entry: /dev/snd dev/snd none bind,optional,create=dir
EOF
    fi

    echo "🔄 Reiniciando contenedor..."
    pct reboot "$CTID"
    sleep 5

    echo "📦 Instalando y configurando Snapclient..."
    pct exec "$CTID" -- bash -c "
      apt update -qq && apt install -yq alsa-utils psmisc ffmpeg wget &&
      cd /root &&
      wget -q https://github.com/badaix/snapcast/releases/download/$SUGGESTED_VER/snapclient_${SUGGESTED_VER#v}-1_amd64_${DEBIAN_VERSION}.deb -O snapclient.deb &&
      apt install -y ./snapclient.deb &&
      usermod -aG audio snapclient &&
      mkdir -p /etc &&
      echo 'defaults.pcm.card $CARD_ID' > /etc/asound.conf &&
      echo 'defaults.ctl.card $CARD_ID' >> /etc/asound.conf &&
      cat > /etc/default/snapclient <<CONF
START_SNAPCLIENT=true
SNAPCLIENT_OPTS=\"--soundcard $ALSA_DEVICE --hostID $CLIENT_NAME tcp://$SNAPSERVER_IP:1704\"
CONF
      amixer -c $CARD_ID sset Master ${VOLUME}% || amixer -c $CARD_ID sset Speaker ${VOLUME}% || amixer -c $CARD_ID sset PCM ${VOLUME}% || true
      alsactl store || true
      systemctl enable snapclient
      systemctl restart snapclient
    "
  else
    apt update -qq && apt install -yq alsa-utils psmisc ffmpeg wget
    cd /root
    wget -q https://github.com/badaix/snapcast/releases/download/$SUGGESTED_VER/snapclient_${SUGGESTED_VER#v}-1_amd64_${DEBIAN_VERSION}.deb -O snapclient.deb
    apt install -y ./snapclient.deb
    usermod -aG audio snapclient 2>/dev/null || true
    mkdir -p /etc
    echo "defaults.pcm.card $CARD_ID" > /etc/asound.conf
    echo "defaults.ctl.card $CARD_ID" >> /etc/asound.conf
    cat > /etc/default/snapclient <<CONF
START_SNAPCLIENT=true
SNAPCLIENT_OPTS="--soundcard $ALSA_DEVICE --hostID $CLIENT_NAME tcp://$SNAPSERVER_IP:1704"
CONF
    amixer -c $CARD_ID sset Master ${VOLUME}% || amixer -c $CARD_ID sset Speaker ${VOLUME}% || amixer -c $CARD_ID sset PCM ${VOLUME}% || true
    alsactl store || true
    systemctl enable snapclient
    systemctl restart snapclient
  fi

  verify_snapclient "$ENVIRONMENT" "$CTID"
}

# === VERIFICAR CONEXIÓN SNAPCLIENT ===========================================

verify_snapclient() {
  local ENV="$1"
  local CT="$2"
  echo ""
  echo "🔍 Verificando conexión Snapclient → Snapserver..."
  sleep 5
  if [ "$ENV" = "proxmox" ]; then
    if pct exec "$CT" -- journalctl -u snapclient -n 50 | grep -q "Connected"; then
      echo "✅ Snapclient conectado correctamente al Snapserver."
    else
      echo "⚠️ No se detectó conexión. Verifica IP del Snapserver, firewall o nombre del dispositivo ALSA."
      pct exec "$CT" -- journalctl -u snapclient -n 20 --no-pager | tail -n 10
    fi
  else
    if journalctl -u snapclient -n 50 | grep -q "Connected"; then
      echo "✅ Snapclient conectado correctamente al Snapserver."
    else
      echo "⚠️ No se detectó conexión. Verifica IP del Snapserver o el dispositivo ALSA."
      journalctl -u snapclient -n 20 --no-pager | tail -n 10
    fi
  fi
  echo ""
  pause
}

# === NUEVA OPCIÓN: VERIFICAR SNAPCLIENT EXISTENTE ============================

verify_existing_snapclient() {
  ENVIRONMENT=$(detect_environment)
  echo ""
  echo "🔎 Verificación de Snapclient existente..."
  if [ "$ENVIRONMENT" = "proxmox" ]; then
    echo ""
    echo "📦 Contenedores disponibles:"
    pct list | awk 'NR>1 {printf " - %s (%s)\n", $1, $2}'
    echo ""
    read -rp "Ingrese el ID del contenedor a verificar: " CTID
    verify_snapclient "proxmox" "$CTID"
  else
    verify_snapclient "$ENVIRONMENT" ""
  fi
}

# === MENÚ PRINCIPAL ==========================================================

clear
echo "═══════════════════════════════════════════════════"
echo "      🎧 SNAPCLIENT AUDIO MANAGER v2025.10.14"
echo "═══════════════════════════════════════════════════"
echo "1️⃣  Fijar orden ALSA del host"
echo "2️⃣  Configurar Snapclient en LXC/Debian"
echo "3️⃣  Ejecutar ambos pasos (recomendado)"
echo "4️⃣  Salir"
echo "5️⃣  🔎 Verificar Snapclient existente"
echo "═══════════════════════════════════════════════════"
read -rp "Selecciona una opción [1-5]: " opt

case "$opt" in
  1) fix_alsa_order ;;
  2) setup_snapclient ;;
  3) fix_alsa_order; setup_snapclient ;;
  4) echo "👋 Saliendo..."; exit 0 ;;
  5) verify_existing_snapclient ;;
  *) echo "❌ Opción inválida."; exit 1 ;;
esac
